import type { FlowStep, FlowVariant } from '@/lib/agents/flows/types'

/**
 * Server-synthesised progress lines for the research panel.
 *
 * WHY THIS EXISTS. The UI already has the Perplexity-shaped container —
 * research-process-section.tsx renders "Working on it — N steps so far" live
 * and "Completed N steps" when done, and it renders `reasoning` parts inside
 * that panel. What it does not have is anything to put in it: measured across
 * 25 prod turns, kimi-k2.6's reasoning window averaged 1.9s and was 1.5s on a
 * 91-second turn. The model is not narrating its own progress, so on a long
 * turn the user watches an empty panel.
 *
 * The obvious fix — telling the model to narrate — is the one that was
 * removed earlier today for good reason: narration emitted as `text` parts
 * lands in the ANSWER area, splits the panel, and is then superseded by the
 * real answer. Tokens billed, latency paid, output discarded.
 *
 * So the progress line is generated by the SERVER from facts it already has
 * (step number, which tools ran), and emitted as a `reasoning` part, which is
 * the part type the panel renders. No model tokens, no latency, and it cannot
 * contradict the answer because it is derived from what actually happened.
 *
 * Two mechanical constraints, both learned from the SDK's stream handling:
 *  - the part id must not collide with a model-emitted reasoning part, hence
 *    the explicit `flow-progress-` prefix;
 *  - `finish-step` clears active reasoning parts, so each line has to be
 *    opened and closed within a single emission rather than left streaming.
 */

/** Minimal view of the writer, so this module needs no SDK types. */
export type ProgressWriter = {
  write: (chunk: Record<string, unknown>) => void
}

export type ProgressEmitter = (input: {
  stepNumber: number
  steps: readonly FlowStep[]
  skipSearch: boolean
}) => void

/**
 * Build an emitter for a variant, or null when the variant defines no status
 * line (baseline, adaptive) — callers should then skip wiring onStepFinish at
 * all rather than installing a no-op.
 */
export function createFlowProgressEmitter(
  flow: FlowVariant,
  writer: ProgressWriter
): ProgressEmitter | null {
  if (!flow.stepStatus) return null

  let seq = 0
  let last: string | null = null

  return ({ stepNumber, steps, skipSearch }) => {
    let text: string | null
    try {
      text = flow.stepStatus!({ stepNumber, steps, skipSearch })
    } catch {
      // A status line must never break the turn it is describing.
      return
    }
    if (!text) return
    // Consecutive identical lines are noise — "Reassessing" three times in a
    // row tells the user nothing and inflates the step counter.
    if (text === last) return
    last = text

    const id = `flow-progress-${flow.id}-${seq++}`
    try {
      writer.write({ type: 'reasoning-start', id })
      writer.write({ type: 'reasoning-delta', id, delta: text })
      writer.write({ type: 'reasoning-end', id })
    } catch {
      // Same contract: telemetry-shaped output never fails the stream.
    }
  }
}
